### ISSUE TITLE
Can we support other LLM mode?

### ISSUE THREAD

**Issue by uripeled2** [trilogy-data/pytrilogy-nlp#11]
I recently published a package [llm-client](https://github.com/uripeled2/llm-client-sdk) that can be very helpful in enabling the support to run other LLM models, including OpenAI, Google, AI21, HuggingfaceHub, Aleph Alpha, Anthropic, Local models with transformers.

**Comment by greenmtnboy** [comment]
We have support for multiple LLM models at this point.
